# Generated by Django 2.2.4 on 2021-03-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
